version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Redis2019!", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    
